version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: cloudstack-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend

  backend:
    build: .
    container_name: cloudstack-api
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: cloudstack-redis